### ISSUE TITLE
/verify on rails doesn't redirect to ID Site

### ISSUE THREAD

**Issue by saimaddali** [stormpath/stormpath-rails#90]
This is similar to /forgot where the end-user isn't redirected to ID Site when they hit /forgot but instead they are taken to the regular view on the integration. The same behavior persists for /verify. Hitting /verify only leads them to the local app and not the ID Site. The same workflow for /forgot should be implemented.

**Comment by cilim** [comment]
@saimaddali currently [the framework spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/idsite.md) isn't defined to have a workflow like that. Also, if you checkout the configuration in the default `stormpath.yml` it doesn't have an endpoint for `verifyUri`.

```
stormpath:
  web:
    idSite:
      enabled: true
      loginUri: ""
      forgotUri: "/#/forgot"
      registerUri: "/#/register"
```

Please discuss with @omgitstom about this topic to determine whether this is a missing feature in the Rails integration or is it intended to work without it.
